name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker-build:
    runs-on: ubuntu-latest
    needs: laravel-tests

    steps:
    - uses: actions/checkout@v4

    # Étape 2 : Login à Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Étape 3 : Construire l'image Docker
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag hakimfidjel/portfolio:latest

    # Étape 4 : Pousser l'image sur Docker Hub
    - name: Push Docker image
      run: docker push hakimfidjel/portfolio:latest
